/**************************************************************************
-- -Generated by xSQL Schema Compare
-- -Date/Time: Aug 06 2013, 01:33:26 PM

-- -Summary:
    T-SQL script that makes the schema of the database [(local)\sqlexpress].[OCM_Staging] 
    the same as the schema of the database [(local)\sqlexpress].[OCM_Live].

-- -Action:
    Execute this script on [(local)\sqlexpress].[OCM_Staging].

    **** BACKUP the database [(local)\sqlexpress].[OCM_Staging] before running this script ****

-- -Source SQL Server version: 11.0.3128.0
-- -Target SQL Server version: 11.0.3128.0
**************************************************************************/

/**************************************************************************
Drops:
	Column [dbo].[MetadataGroup].[GroupOwnerUserID] will be dropped.
**************************************************************************/

USE [OCM_Staging]
GO

SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET XACT_ABORT ON
GO


BEGIN TRANSACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataGroup] DROP CONSTRAINT [FK_MetadataGroup_User]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataGroup] DROP COLUMN [GroupOwnerUserID]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataGroup] ADD [DataProviderID] [int] NOT NULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataGroup] ADD [IsPublicInterest] [bit] CONSTRAINT [DF_MetadataGroup_IsPublicInterest] DEFAULT ((0)) NOT NULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DataProvider] ADD [IsRestrictedEdit] [bit] CONSTRAINT [DF_DataProvider_IsRestrictedEdit] DEFAULT ((0)) NOT NULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataValue] ADD [MetadataFieldOptionID] [int] NULL
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DataProviderUser]
(
	[ID] [int] IDENTITY(1,1),
	[DataProviderID] [int] NOT NULL,
	[UserID] [int] NOT NULL,
	[IsDataProviderAdmin] [bit] NOT NULL
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DataProviderUser] ADD CONSTRAINT [DF_DataProviderUser_IsDataProviderAdmin] DEFAULT ((0)) FOR [IsDataProviderAdmin]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MetadataFieldOption]
(
	[ID] [int] IDENTITY(1,1),
	[MetadataFieldID] [int] NOT NULL,
	[Title] [nvarchar](100) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DataProviderUser] ADD CONSTRAINT [PK_DataProviderUser] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataFieldOption] ADD CONSTRAINT [PK_MetadataFieldOption] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DataProviderUser] WITH CHECK ADD CONSTRAINT [FK_DataProviderUser_DataProvider] FOREIGN KEY
(
	[DataProviderID]
)
REFERENCES [dbo].[DataProvider]
(
	[ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[DataProviderUser] WITH CHECK ADD CONSTRAINT [FK_DataProviderUser_User] FOREIGN KEY
(
	[UserID]
)
REFERENCES [dbo].[User]
(
	[ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataGroup] WITH CHECK ADD CONSTRAINT [FK_MetadataGroup_DataProvider] FOREIGN KEY
(
	[DataProviderID]
)
REFERENCES [dbo].[DataProvider]
(
	[ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataFieldOption] WITH CHECK ADD CONSTRAINT [FK_MetadataFieldOption_MetadataField] FOREIGN KEY
(
	[MetadataFieldID]
)
REFERENCES [dbo].[MetadataField]
(
	[ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[MetadataValue] WITH CHECK ADD CONSTRAINT [FK_MetadataValue_MetadataFieldOption] FOREIGN KEY
(
	[MetadataFieldOptionID]
)
REFERENCES [dbo].[MetadataFieldOption]
(
	[ID]
)
ON DELETE NO ACTION
ON UPDATE NO ACTION
GO


COMMIT TRANSACTION
GO


